TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

ARCHIVE += sioc-li21-bl01.archive
ARCHIVE += sioc-li24-bl01.archive

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
