TOP=../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE


#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

# Databases
# --------------------------------------------------
DB += motionCtrlRB.db
DB += lcls2FPGA.db
DB += motionCtrl.db
DB += msgStatus.db
DB += blen_gap_coefI2.db
DB += tempProcess.db
DB += initMode.db
DB += initMotion.db

# Autosave
# --------------------------------------------------
REQ += common.req
REQ += pyro.req


include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

