TOP=../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE


#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

# Main User-visible PVs 
# --------------------------------------------------
DB += blenLCLS2.db


# DBs containing Expert PVs and other routines
# --------------------------------------------------
DB += lcls2FPGA.db
DB += pyroFilters.db
DB += msgStatus.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

