TOP = ..
include $(TOP)/configure/CONFIG
#DIRS += $(wildcard *ioc*)
DIRS += sioc-b084-bl03 sioc-b084-bl04 sioc-b34-bl03 sioc-bc1b-bl01 sioc-bc2b-bl01 sioc-htr-bl01
DIRS += $(wildcard as*)
include $(CONFIG)/RULES_DIRS

