##############################################################################
## This file is part of 'LCLS2 Common Carrier Core'.
## It is subject to the license terms in the LICENSE.txt file found in the
## top-level directory of this distribution and at:
##    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html.
## No part of 'LCLS2 Common Carrier Core', including this file,
## may be copied, modified, propagated, or distributed except according to
## the terms contained in the LICENSE.txt file.
##############################################################################
#schemaversion 3.0.0
#once

DspCoreConfigMr: &DspCoreConfigMr
  description: "Sysgen configuration registers"
  class: MMIODev
  configPrio: 1
  size: 0x010000
  #########
  children:
  #########
    #########################################################
    Version:
      class: IntField
      at:
        offset: 0x0000
      sizeBits: 32
      mode: RO
      description: "System generator core version"
    #########################################################
    CoefA0:
      class: IntField
      at:
        offset: 0x0004
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Coef A0 of processig equation to properly scale the first averaged group"
    #########################################################
    CoefA1:
      class: IntField
      at:
        offset: 0x0008
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Coef A1 of processig equation to properly scale the second averaged group"
    #########################################################
    CoefA2:
      class: IntField
      at:
        offset: 0x000C
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Coef A2 of processig equation to properly scale the third averaged group"
    #########################################################
    CoefB:
      class: IntField
      at:
        offset: 0x0010
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Coef B of processig equation to scale TMIT * BRAW product value (first term)"
    #########################################################
    CoefC:
      class: IntField
      at:
        offset: 0x0014
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Coef C of processig equation - power of TMIT value (first term)"
    #########################################################
    CoefD:
      class: IntField
      at:
        offset: 0x0018
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Coef D of processig equation - power of BRAW vlaue(first term)"
    #########################################################
    CoefE:
      class: IntField
      at:
        offset: 0x001C
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Coef E of processig equation to scale TMIT * BRAW product value (second term)"
    #########################################################
    CoefF:
      class: IntField
      at:
        offset: 0x0020
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Coef F of processig equation - power of TMIT value (second term)"
    #########################################################
    CoefG:
      class: IntField
      at:
        offset: 0x0024
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Coef G of processig equation - power of BRAW vlaue(second term)"
    #########################################################
    CoefH:
      class: IntField
      at:
        offset: 0x0028
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Coef A2 of processig equation to properly scale the TMIT value"
    #########################################################
    MultResultA0:
      class: IntField
      at:
        offset: 0x0100
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "Floating - Result of multiplication of ADC average 0 and A0 coef"
    #########################################################
    MultResultA1:
      class: IntField
      at:
        offset: 0x0104
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "Floating - Result of multiplication of ADC average 1 and A1 coef"
    #########################################################
    MultResultA2:
      class: IntField
      at:
        offset: 0x0108
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "Floating - Result of multiplication of ADC average 2 and A2 coef"
    #########################################################
    MultResultH:
      class: IntField
      at:
        offset: 0x010C
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "Floating - Result of multiplication of TMIT value and H coef"
    #########################################################
    AddSums0:
      class: IntField
      at:
        offset: 0x0110
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "Floating - Result of addition of MultResultA0 and A1"
    #########################################################
    AddSums1:
      class: IntField
      at:
        offset: 0x0114
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "Floating - Result of addition of MultResultA0_A1 and A3- BRaw"
    #########################################################
    LnOfBRaw:
      class: IntField
      at:
        offset: 0x0118
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "Floating - Result of Ln function of Braw"
    #########################################################
    MultLnBrawD:
      class: IntField
      at:
        offset: 0x011C
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "Floating - Result of muliplication of Ln(BRaw) by  Dcoef"
    #########################################################
    LnOfTMIT:
      class: IntField
      at:
        offset: 0x0120
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "Floating - Result of Ln function of TMIT"
    #########################################################
    MultLnTmitC:
      class: IntField
      at:
        offset: 0x0124
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "Floating - Result of muliplication of Ln(TMIT) by  Ccoef"
    #########################################################
    AddSums2:
      class: IntField
      at:
        offset: 0x0128
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "Floating - Result of addition MultLnTmitC and MultLnBrawD"
    #########################################################
    AddSums3:
      class: IntField
      at:
        offset: 0x012C
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "loating - Result of addition AddSums2 and CoefB"
    #########################################################
    ExpResult0:
      class: IntField
      at:
        offset: 0x0130
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "Floating - Result of exponent of AddSums3"
    #########################################################
    LnOfBRaw2:
      class: IntField
      at:
        offset: 0x0134
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "Floating - Result 2 of Ln function of Braw"
    #########################################################
    MultLnBrawG:
      class: IntField
      at:
        offset: 0x0138
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "Floating - Result of muliplication of Ln(BRaw) by  Gcoef"
    #########################################################
    LnOfTMIT2:
      class: IntField
      at:
        offset: 0x013C
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "Floating - Result 2 of Ln function of TMIT"
    #########################################################
    MultLnTmitF:
      class: IntField
      at:
        offset: 0x0140
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "Floating - Result of muliplication of Ln(TMIT) by  Fcoef"
    #########################################################
    AddSums4:
      class: IntField
      at:
        offset: 0x0144
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "Floating - Result of addition MultLnTmitF and MultLnBrawG"
    #########################################################
    AddSums5:
      class: IntField
      at:
        offset: 0x0148
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "Floating - Result of addition AddSums4 and CoefE"
    #########################################################
    ExpResult1:
      class: IntField
      at:
        offset: 0x014C
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "Floating - Result of exponent of AddSums5"
    #########################################################
    FinalSum:
      class: IntField
      at:
        offset: 0x0150
      encoding: IEEE_754
      sizeBits: 32
      mode: RO
      description: "Floating - Result of calculation - Sum of ExpResult0 and ExpResult1"
    #########################################################
    Scratch:
      class: IntField
      at:
        offset: 0x0FFC
      sizeBits: 32
      mode: RW
      description: "Scratch register"
    #########################################################
    